apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-external-secrets-vault-cm
data:
  VAULT_ADDR: https://vault-vault.{{ .Values.global.hubClusterDomain }}
  NODE_EXTRA_CA_CERTS: "/usr/local/share/ca-certificates/ca.crt"
