apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-82
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-82
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-83
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-83
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-84
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-84
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-85
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-85
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-86
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-86
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-158
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-158
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-167
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-167
    importPolicy: {}
    referencePolicy:
      type: Local
