apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  tags:
  - name: 0.3.2-65
    from:
      kind: DockerImage
      name: quay.io/beekhof/iot-consumer:0.3.2-65
    importPolicy: {}
    referencePolicy:
      type: Local
