apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-181
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-181
    importPolicy: {}
    referencePolicy:
      type: Local
