apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  host: messaging-manuela-stormshift-messaging.apps.claudiol-factory.blueprints.rhecoeng.com
  port:
    targetPort: 3000-tcp
  to:
    kind: Service
    name: messaging
    weight: 100
  wildcardPolicy: None
status:
  ingress: []

