global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: mhjacks
    username: mhjacks
    email: mhjacks@redhat.com
    dev_revision: main
    targetRevision: main

  quay:
    provider: quay.io
    account: martjack

  datacenter:
    domain: blueprints.rhecoeng.com
    clustername: mhjacks-dc
