global:
  valuesDirectoryURL: https://github.com/dagger-refuse-cool/edge-gitops/raw/main/
  options:
    useCSV: True
    syncPolicy: Manual
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  quay:
    provider: quay.io
    account: PLAINTEXT
