global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: MB-ID
    username: MB-ID
    email: eng.mohammed.belal@gmail.com
    dev_revision: odf

  quay:
    provider: quay.io
    account: msamymos

  datacenter:
    clustername: PLAINTEXT
    domain: PLAINTEXT

  edge:
    clustername: PLAINTEXT
    domain: PLAINTEXT

