global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: EMAIL@EXAMPLE.COM
    dev_revision: main
    targetRevision: main

  quay:
    provider: quay.io
    account: PLAINTEXT

  datacenter:
    domain: PLAINTEXT
    clustername: PLAINTEXT
