global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: claudiol
    username: claudiol
    email: claudiol@redhat.com
    dev_revision: main

  quay:
    provider: quay.io
    account: claudiol

  datacenter:
    clustername: claudiol-dc
    domain: blueprints.rhecoeng.com
  edge:
    clustername: claudiol-dc
    domain: blueprints.rhecoeng.com
