global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: ipbabble
    username: ipbabble
    email: whenry@redhat.com
    dev_revision: main

  quay:
    provider: quay.io
    account: ipbabble

  datacenter:
    clustername: wh-datacenter
    domain: blueprints.rhecoeng.com

  edge:
    clustername: wh-factory
    domain: blueprints.rhecoeng.com
