main:
  siteName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  datacenter:
    clustername: datacenter-XXXXX
    domain: BASEDOMAIN

  edge:
    clustername: edge-XXXXX
    domain: BASEDOMAIN
