global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: mhjacks
    username: 'Martin Jackson'
    email: mhjacks@redhat.com
    dev_revision: main

  quay:
    provider: quay.io
    account: martjack

  datacenter:
    clustername: mhjacks-dc
    domain: blueprints.rhecoeng.com
