global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

namespaces:
- open-cluster-management
- policy

applications:
- name: acm
  repoURL: https://github.com/dagger-refuse-cool/edge-gitops.git
  project: datacenter
  path: applications/acm

subscriptions:
- name: advanced-cluster-management
  namespace: open-cluster-management
  source: redhat-operators
  channel: release-2.3
  csv: v2.3.1
