global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: EMAIL@EXAMPLE.COM
    dev_revision: main
    ops_revision: main

  quay:
    provider: quay.io
    account: PLAINTEXT

  datacenter:
    domain: PLAINTEXT
    clustername: PLAINTEXT
