apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: factorydatacenter
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: manuela-factory
spec:
  description: manuela factorydatacenter
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
