apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-test-run-
  namespace: manuela-ci
  labels:
    argocd.argoproj.io/instance: pipelines-manufacturing-edge-ai-ml-datacenter
    tekton.dev/pipeline: build-and-test
spec:
  params:
    - name: DEV_REVISION
      value: main
    - name: OPS_REVISION
      value: main
  pipelineRef:
    name: build-and-test
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: gitrepos
      persistentVolumeClaim:
        claimName: gitrepos-rwo
    - configMap:
        name: environment
      name: config
    - name: github-secret
      secret:
        secretName: github
    - name: argocd-env-secret
      secret:
        secretName: argocd-env
    - name: build-artifacts
      persistentVolumeClaim:
        claimName: build-artifacts-rwo
    - name: quay-secret
      secret:
        secretName: quay-build-secret
