apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-opendatahub
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: manuela
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
    path: manufacturing-edge-ai-ml/datacenter/opendatahub
    targetRevision: {{ .Values.global.git.target }}
    #kustomize: {}
    #namePrefix: manuela
  syncPolicy:
    automated: {}
