global:
  git:
    provider: github.com
    account: claudiol
    email: claudiol@redhat.com
    username: claudiol
    dev_revision: main

  quay:
    provider: quay.io
    account: claudiol

  datacenter:
    clustername: claudiol-factory
    domain: blueprints.rhecoeng.com

  edge:
    clustername: EDGE-CLUSTERNAME
    domain: EDGE-DOMAINNAME

  deploy:
    site: factory

messaging:
  vibrationAlert: true
  vibrationAnomaly: true 
  nodeTlsReject: 0

machineSensor1:
  port: 80

machineSensor2:
  port: 80
  sensorTemperature: false

mqtt:
  broker:
    uri: "tcp://broker-amq-mqtt-all-0-svc:61616"
    clientId: "MQTT2KafkaRoute"
    topic:
      temperature: "iot-sensor/sw/temperature"
      vibration: "iot-sensor/sw/vibration"

kafka:
  broker:
    uri: "manuela-kafka-cluster-kafka-bootstrap:9092"
    topic:
      temperature: "iot-sensor-sw-temperature"
      vibration: "iot-sensor-sw-vibration"

secrets:
  # NEVER COMMIT THESE VALUES TO GIT
  enabled: false
  quay:
    # Quay -> Robot Accounts -> Kubernetes Secret -> View
    authToken: BASE64STRING

  git:
    # Go to: https://github.com/settings/tokens
    # Then: echo -n 'your string value' | base64
    authToken: BASE64STRING
    accountToken: BASE64STRING
