global:
  git:
    provider: github.com
    account: claudiol
    email: claudiol@redhat.com
    username: claudiol
    dev_revision: main

  quay:
    provider: quay.io
    account: claudiol

  datacenter:
    clustername: claudiol-factory
    domain: blueprints.rhecoeng.com

  edge:
    clustername: EDGE-CLUSTERNAME
    domain: EDGE-DOMAINNAME

  deploy:
    site: factory

messaging:
  vibrationAlert: true
  vibrationAnomaly: true
  nodeTlsReject: 0 

machineSensor1:
  port: 80

machineSensor2:
  port: 80
  sensorTemperature: true

secrets:
  # NEVER COMMIT THESE VALUES TO GIT
  enabled: false
  quay:
    # Quay -> Robot Accounts -> Kubernetes Secret -> View
    authToken: BASE64STRING

  git:
    # Go to: https://github.com/settings/tokens
    # Then: echo -n 'your string value' | base64
    authToken: BASE64STRING
    accountToken: BASE64STRING
