apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: {{ .Values.installPlanApproval }}
  name: seldon-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.{{ .Values.subscriptions.version.seldon }}

#install-seldon-operator:
#	oc new-project test-anomaly-detection
#	oc apply -f manifests/test-anomaly-detection-operatorgroup.yaml
#	oc apply -f manifests/seldon-subscription-v1.2.0.yaml
