site:
  name: datacenter

global:
  pattern: industrial-edge
  repoURL: "https://github.com/beekhof/industrial-edge.git"
  targetRevision: main

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay
