apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-pipelines
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: manuela
spec:
  destination:
    name: in-cluster
    namespace: manuela-ci
  project: datacenter
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
    path: manufacturing-edge-ai-ml/datacenter/pipelines
    targetRevision: {{ .Values.global.git.ops_revision }}
    plugin:
      env:
      - name: BLUEPRINT_VERSION
        value: 0.0.1
      name: helm-with-kustomize
{{- if eq .Values.gitops.syncPolicy "Automatic" }}
  syncPolicy:
    automated: 
      prune: false
      selfHeal: false
{{- end }}
