apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: preview
  installPlanApproval: {{ .Values.subscriptions.installPlanApproval }}
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: redhat-openshift-pipelines.{{ .Values.subscriptions.version.pipelines }}
