apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: {{ .Values.subscriptions.version.opendatahub.pipelines.channel }}
  installPlanApproval: {{ .Values.subscriptions.installPlanApproval }}
  name: openshift-pipelines-operator-rh
  source: {{ .Values.subscriptions.version.pipelines.source }}
  sourceNamespace: openshift-marketplace
{{- if eq .Values.subscriptions.useCSV "True" }}
  startingCSV: redhat-openshift-pipelines.{{ .Values.subscriptions.version.pipelines.csv }}
{{- end }}

