apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
  namespace: manuela-stormshift-machine-sensor
spec:
  tags:
  - name: 0.3.1-35
    from:
      kind: DockerImage
      name: quay.io/beekhof/iot-software-sensor:0.3.1-35
    importPolicy: {}
    referencePolicy:
      type: Local
