apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: seldon-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.v1.7.0
