bootstrap:
  enabled: false

global:
  git:
    provider: github.com
    account: PLAINTEXT

    # Go to: https://github.com/settings/tokens
    # Then: echo -n 'your string value' | base64
    authToken: BASE64STRING
    accountToken: BASE64STRING

  quay:
    provider: quay.io
    account: PLAINTEXT

    # Quay -> Robot Accounts -> Kubernetes Secret -> View
    authToken: BASE64STRING
