apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: manuela
  namespace: manuela
  labels:
    app.kubernetes.io/instance: manuela
spec:
  description: manuela blueprint
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
