apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela
  namespace: manuela-ci
  labels:
    app.kubernetes.io/instance: manuela
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
    path: manufacturing-edge-ai-ml/charts/applications
    targetRevision: {{ .Values.global.git.target }}
    kustomize:
      commonLabels: manuela-opendatahub
      #namePrefix: manuela
  syncPolicy:
    automated: {}
