apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-subscriptions
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: manuela
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
    path: manufacturing-edge-ai-ml/charts/subscriptions
    targetRevision: {{ .Values.global.git.target }}
    helm:
      releaseName: manuela-release-v1
      parameters:
      - name: installPlanApproval
        value: {{ .Values.installPlanApproval }}
      - name: version.gitops
        value: {{ .Values.version.gitops }}
      - name: version.pipelines
        value: {{ .Values.version.pipelines }}
      - name: version.acm
        value: {{ .Values.version.acm }}
      - name: version.opendatahub
        value: {{ .Values.version.opendatahub }}
      - name: global.git.provider
        value: {{ .Values.global.git.provider }}
      - name: global.git.account
        value: {{ .Values.global.git.account }}
      - name: global.git.target
        value: {{ .Values.global.git.target }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
