apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-data-lake
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.username }}/blueprints.git
    targetRevision: {{ .Values.global.git.target }}
    path: manufacturing-edge-ai-ml/factory/instances/manuela-data-lake/
  destination:
    server: https://kubernetes.default.svc
    namespace: manuela-data-lake
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
  - group: image.openshift.io
    kind: ImageStream
    jsonPointers:
    - /spec/tags
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
