global:
  datacenter:
    clustername: claudiol-dc1
    domain: blueprints.rhecoeng.com

messaging:
  vibrationAlert: true
  vibrationAnomaly: true 
  nodeTlsReject: 0

machineSensor1:
  port: 80

machineSensor2:
  port: 80
  sensorTemperature: false


