apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Seed Pipelines to build individual component images using RWO PVCs
- seed-iot-anomaly-detection.yaml
- seed-iot-consumer.yaml
- seed-iot-frontend.yaml
- seed-iot-software-sensor.yaml
- seed.yaml
