apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: anomaly-detection
  name: anomaly-detection
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.3.2-19
    from:
      kind: DockerImage
      name: quay.io/abeekhof/iot-anomaly-detection:0.3.2-19
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-54
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-54
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-56
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-56
    importPolicy: {}
    referencePolicy:
      type: Local
