apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: anomaly-detection
  name: anomaly-detection
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.3.2-57
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-57
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-58
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-58
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-59
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-59
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-60
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-60
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-61
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-61
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-91
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-anomaly-detection:0.3.2-91
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-100
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-anomaly-detection:0.3.2-100
    importPolicy: {}
    referencePolicy:
      type: Local
