apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-50
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-consumer:0.3.2-50
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-52
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-52
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-53
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-53
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-63
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-63
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-65
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-65
    importPolicy: {}
    referencePolicy:
      type: Local
