apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: {{ $.Values.global.pattern }}-{{ .Values.site.name }}
  # The name here needs to be consistent with
  # - acm/templates/policies/application-policies.yaml
  # - site/templates/applications.yaml
  # - any references to secrets and route URLs in documentation
  name: {{ $.Values.global.pattern }}-{{ .Values.site.name }}
spec: {}
