{{- range .Values.site.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: {{ default "pattern" $.Release.name }}
    argocd.argoproj.io/managed-by: {{ $.Values.global.pattern }}-{{ $.Values.site.name }}
  name: {{ . }}
spec:
---
{{- end }}
