---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: image-registry-credentials
  namespace: manuela-ci
spec:
  backendType: vault
  data:
    - key: {{ .Values.imageregistry.key }}
      name: username
      property: username
    - key: {{ .Values.imageregistry.key }}
      name: password
      property: password
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: image-registry-credentials
      namespace: manuela-ci
      annotations:
        # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
        tekton.dev/docker-0: https://{{ .Values.global.imageregistry.hostname }}
    type: kubernetes.io/basic-auth
  vaultMountPoint: {{ .Values.vault.mountPoint }}
  vaultRole: {{ .Values.vault.role }}
