---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: git-repo-credentials
  namespace: manuela-ci
spec:
  backendType: vault
  data:
    - key: {{ .Values.gitsecret.key }}
      name: username
      property: username
    - key: {{ .Values.gitsecret.key }}
      name: password
      property: password
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: git-repo-credentials
      namespace: manuela-ci
      annotations:
        # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
        tekton.dev/git-0: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}
    type: kubernetes.io/basic-auth
  vaultMountPoint: {{ Values.vault.mountPoint }}
  vaultRole: {{ Values.vault.role }}
