apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-datacenter
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: manuela
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
    path: manufacturing-edge-ai-ml/datacenter/main
    targetRevision: {{ .Values.global.git.target }}
    helm:
      releaseName: manuela-release-v1
      parameters:
      - name: subscriptions.installPlanApproval
        value: {{ .Values.subscriptions.installPlanApproval }}
      - name: subscriptions.version.gitops
        value: {{ .Values.subscriptions.version.gitops }}
      - name: subscriptions.version.pipelines
        value: {{ .Values.subscriptions.version.pipelines }}
      - name: subscriptions.version.acm
        value: {{ .Values.subscriptions.version.acm }}
      - name: subscriptions.version.opendatahub
        value: {{ .Values.subscriptions.version.opendatahub }}
      - name: subscriptions.version.seldon
        value: {{ .Values.subscriptions.version.seldon }}
      - name: global.quay.provider
        value: {{ .Values.global.quay.provider }}
      - name: global.quay.account
        value: {{ .Values.global.quay.account }}
      - name: global.git.provider
        value: {{ .Values.global.git.provider }}
      - name: global.git.account
        value: {{ .Values.global.git.account }}
      - name: global.git.target
        value: {{ .Values.global.git.target }}
      - name: global.git.email
        value: {{ .Values.global.git.email }}
      - name: global.git.username
        value: {{ .Values.global.git.username }}
      - name: global.datacenter.domain
        value: {{ .Values.global.datacenter.domain }}
      - name: global.datacenter.clustername
        value: {{ .Values.global.datacenter.clustername }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
