apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.1-42
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-42
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-42
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-42
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-43
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-43
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-44
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-44
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-45
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-45
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-47
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-47
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-48
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-48
    importPolicy: {}
    referencePolicy:
      type: Local
