kind: Secret
apiVersion: v1
metadata:
  name: s3-secret
  namespace: manuela-data-lake-factory-s3-store
type: Opaque  
data:
  # As the original developers point out to themselves in kafka-tls-certificate-and-key.yaml
  #
  #    It is beyond a bad practise to check in private keys into git repos
  #
  # Pre-create as part of the initial 'helm install' chart
  application.properties: ICBzMy5hY2Nlc3NLZXk6IEN4ZkJCQlZGV1hEZGo1ek50MjZhCiAgczMuc2VjcmV0S2V5OiBjMXpNaVVJSnhJVjBMR3RyeXVDaTJEaDB2R0JtdUdtRzdNbE42YzdSCg==
