apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: centraldatacenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/manuela-gitops.git
    targetRevision: HEAD
    path: deployment/hub-centraldatacenter
