---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: s3-secret
  namespace: external-secrets
spec:
  backendType: vault
  data:
    - key: {{ .Values.s3secret.key }}
      name: application.properties
      property: s3Secret
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: s3-secret
      namespace: external-secrets
    type: Opaque
  vaultMountPoint: {{ .Values.vault.mountPoint }}
  vaultRole: {{ .Values.vault.role }}
