---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: s3-secret
  namespace: external-secrets
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: s3-secret
    creationPolicy: Owner
    template:
      type: Opaque
  stringData:
    - secretKey: "application.properties"
      remoteRef:
        key: {{ .Values.s3secret.key }}
        property: s3Secret
