---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: s3-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: s3-secret
    creationPolicy: Owner
  data:
    - secretKey: "application.properties"
      remoteRef:
        key: {{ .Values.s3secret.key }}
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: s3-secret
      namespace: external-secrets
    type: Opaque
