apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-cluster-management-registry
  labels:
    app: open-cluster-management-registry
spec:
  selector:
    matchLabels:
      app: open-cluster-management-registry
  template:
    metadata:
      labels:
        app: open-cluster-management-registry
    spec:
      containers:
      - name: multiclusterhub-operator-index
        image: multiclusterhub-operator-index:1.0.0
        ports:
        - containerPort: 50051
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret