kind: Service
apiVersion: v1
metadata:
  name: open-cluster-management-registry
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: open-cluster-management-registry