apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opendatahub-operator
  namespace: openshift-operators
spec:
  channel: beta
  installPlanApproval: {{ .Values.subscriptions.installPlanApproval }}
  name: opendatahub-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: opendatahub-operator.{{ .Values.subscriptions.version.opendatahub }}

